feat: add sendable config for useWatcher
alovajs/alova pull request #177
Opened 2023-08-03 15:54 UTC by changlin2569

作者你好，试着写了写 https://github.com/alovajs/alova/issues/176#issue-1830651630 这个问题，目前只写了 React 和 Svelte 部分，麻烦您看一下我的方向是对的吗？

[English]
Hello author, I tried to write https://github.com/alovajs/alova/issues/176#issue-1830651630 This problem, currently only wrote the React and Svelte part, please take a look at my direction is right ?

2023-08-04 03:30 UTC, JOU-amjs commented
@changlin2569 收到你的PR我真的非常开心，这是alova的第一个PR

我看了你的代码，写的很漂亮，例如使用了默认`sendable`函数做兼容处理，写法也符合alova的开发规范，值得点赞。

可能由于对alova库还不够熟悉，实现思路上我有几个小小的建议希望可以改动的。

你的思路是通过`statesHook`的方式来控制是否发送，可能这种方式不够简洁， `statesHook`是UI框架的钩子，它其实也允许开发者自定义，例如`solidjs/qwik`或其他不那么知名的UI框架，因此我觉得`statesHook`内应该尽量保持简洁。

alova的三个核心函数
1. `createRequestState`的职责是初始化use hook
2. `useHookToRequest`的职责是使用use hook发送请求时的一些列操作例如处理hook配置、触发中间件函数、触发响应回调等，由use hook触发的所有请求都会经过这个函数
3. `sendRequest`的职责是处理具体的请求发送以及发送请求相关的功能

因此，我觉得更简洁的方式可以在`useHookToRequest`函数开始位置统一调用`sendable`，这边可以通过`useHookConfig`获取到`sendable`，也可以获取到传入`sendable`内的所有参数，如`methodInstance`、`sendCallingArgs`。如果不可发送则返回一个`Promise.resolve()`兼容一下，不知你觉得我这个方法如何？

2023-08-04 03:33 UTC, JOU-amjs commented
然后还可以添加一下close #176来标记一下关闭issue，合并后将会自动关闭对应issue

2023-08-04 03:36 UTC, JOU-amjs commented on src/functions/createRequestState.ts
> +        return !!sendable({
这边可以

2023-08-04 17:53 UTC, changlin2569 commented
作者大哥你好 我按照你的建议修改了代码  但是我发现设置了 sendable 的 Vue 的单测会超时，并且在 useHookToRequest 之前调用 createAlovaEvent 创建事件对象时，fromCache 应该怎样取值呢？
![d72b22c2ac16da8d10c8eddca99ad49](https://github.com/alovajs/alova/assets/56384788/c870f230-6821-46d7-adc2-9c4b59af78e5)

2023-08-05 00:42 UTC, JOU-amjs commented
> 好的好的 谢谢作者的建议 我确实是第一次提 PR ，我会再看看相关代码结合你的修改建议进行修改

 👏🏻已经很好了，为了保持库的高质量，提PR修改也是正常的

2023-08-06 15:34 UTC, changlin2569 commented
作者你好 现在还是这么几个问题比较困扰 就是设置了 sendable 的 Vue 的单测会超时，并且在 useHookToRequest 之前调用 createAlovaEvent 创建事件对象时，fromCache 应该怎样取值呢？

2023-08-07 05:58 UTC, JOU-amjs commented
> 作者你好 现在还是这么几个问题比较困扰 就是设置了 sendable 的 Vue 的单测会超时，并且在 useHookToRequest 之前调用 createAlovaEvent 创建事件对象时，fromCache 应该怎样取值呢？

@changlin2569 你好，我的意思不是说在`useHookToRequest`调用之前判断`sendable`和创建事件对象，而是在`useHookToRequest`这个函数里面的开头处判断，你可以再仔细看下我的review解释，已经有回答到这边的问题。

关于vue单测里会超时的情况，可能需要你再把对应的单测上传后再调试才能知道问题。

你可以再按我们沟通的结果修改试试，已经差不多接近完成了，加油，祝成功！🤞🤞🤞

2023-08-07 15:43 UTC, changlin2569 commented
作者你好 我按照沟通的结果修改了一下代码  关于 Vue 超时的单测也上传了  麻烦你帮忙给 review 一下😁

2023-08-08 06:44 UTC, JOU-amjs commented
@changlin2569 已经review了，具体请看上面的review，review的内容跑到和上次review的一起了，你可以逐个仔细再看一下，
![image](https://github.com/alovajs/alova/assets/29848971/66ca19a8-9560-4734-a0e7-30362c5d61c6)

整理了下，目前包含以下问题：
1. `sendable`类型应该还是需要放在WatcherHookConfig中；
2. 当报错时也不应该触发请求，因此_sendable需要设置为false，而且不需要用`console.error`输出额外的信息
3. `createAlovaEvent`中事件名称应该改为`AlovaEvent`更加合适，保持和ts一致
4. 再次描述了下`fromCache`应该如何传入的问题
5. 单元测试超时原因是因为sendable返回值固定为false了

另外，还有两个额外的问题我想再说一下的
1. 单元测试应该再覆盖一下`sendable`函数报错的情况
2. git commit message目前都标记为了`feat`，是不符合的，由于我们设置了在发布时自动提取git message作为发布日志，多个`feat`会导致出现多条新特性发布，但其实这只有一个新特性，你可以使用`refactor`标记，因此需要再麻烦修改一下git commit message

请再仔细地过一遍问题，加油！✌

2023-08-08 15:31 UTC, changlin2569 commented
作者你好，我重新改了下，刚开始不熟练 git ，已经把 commit message 修改了，报错单测也补了，还有其他的地方，但是 Vue 的单测这部分我还是没明白  如果原因是因为 sendable 返回值固定为false ，那么 sendable 报错也是默认 false ，但是也应该有返回值而不是超时，我是这样理解的😁（关于 Vue 的单测我也上传了）

2023-08-09 04:16 UTC, JOU-amjs commented
@changlin2569 因为你在单元测试里写了`await untilCbCalled(onSuccess)`，这句话会等待请求成功后才继续往下执行，但在`sendable`中阻止了请求发送，自然也不会有响应，因此就卡在这边不往下执行了，直到报超时错误。

PR已经完成得差不多了，只是关于将`createAlovaEvent`中的`fromCache`改为可选参数的问题，以及单测超时的问题。我已经帮你把这些修改了，修改的内容[点此查看](https://fictional-sniffle-gxjpwgg6q64hwxjv.github.dev/)，你帮忙commit一下即可。

在修改过程中，还发现了一个未测试的问题，就是在成功阻止请求时，还需要将`loading`状态改回false，这是因为在useWatcher中`immediate`为true时，`loading`状态初始值为true，需要恢复，并且也已经增加了单元测试在里面。

2023-08-09 11:50 UTC, changlin2569 commented
@JOU-amjs 这个链接好像是是 cloudIDE 这种，我打开是 404 🤔

2023-08-09 13:57 UTC, JOU-amjs commented
@changlin2569 我这也打不开了，不会丢失了吧😂，现在电脑不在身边，明早我再看一下

2023-08-10 01:17 UTC, JOU-amjs requested changes

2023-08-10 03:13 UTC, merged

2023-08-10 03:14 UTC, JOU-amjs commented
@changlin2569 昨天的已经丢失了😂，现在重新写过了一份合并成功了。

2023-08-10 03:16 UTC, JOU-amjs reviewed
mistakev review

2023-08-10 03:18 UTC, JOU-amjs commented
:tada: This PR is included in version 2.10.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/alova/v/2.10.0)
- [GitHub release](https://github.com/alovajs/alova/releases/tag/v2.10.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-10 03:25 UTC, JOU-amjs commented
@changlin2569 有兴趣再添加一下相应的文档内容吗？[文档内容在这](https://github.com/alovajs/alovajs.github.io)，可以把它添加到`useWatcher章节`中，包含中英文，可以先写中文再用软件翻译成英文。

2023-08-10 03:27 UTC, changlin2569 commented
@JOU-amjs 好的好的 等下班后我再补完文档 第一次 PR 感谢作者非常耐心的给我讲解😀

2023-08-10 03:30 UTC, JOU-amjs commented
哈哈，你也很耐心，为了让库的质量更高点每天晚上改代码，很荣幸有你这样的支持者。😎
虽然持续时间长了点，但这是一个好的开始！