chore: add send function type automatic inference (#158)
alovajs/alova pull request #375
Opened 2024-06-08 14:48 UTC by czhlin

**相关 Issue / Related Issue**

[Issue ID]

**这个 PR 是什么类型？/ What type of PR is this?**

- [ ] 错误修复 (Bug Fix)
- [ ] 新功能 (Feature)
- [ ] 代码重构 (Refactor)
- [ ] TypeScript 类型定义修改 (Typings)
- [ ] 文档修改 (Docs)
- [ ] 代码风格更新 (Code style update)
- [ ] 其他，请描述 (Other, please describe):

**这个 PR 做了什么？/ What does this PR do?**

[简要描述所做更改 / Describe the changes briefly]

**文档 / Docs**

[此次 PR 的文档 / Docs for this PR]

**测试 / Testing**

[描述测试结果 / Describe the test results.]

2024-06-09 06:25 UTC, JOU-amjs requested changes
哇，非常感谢你的贡献，没想到昨天那么快就写完了，太棒了。

我review了，整体思路还是正确的，细节部分可能还需要改进下，具体写在了review中了，然后alova还有`useWatcher`的`send`，以及`useFetcher`的`fetch`也可以一并修改了，真的非常感谢。

2024-06-09 06:25 UTC, JOU-amjs commented on src/hooks/useRequest.ts
>  ) {
这边有三个问题：
1. send函数虽然自动推断了，但即使不传也不会报错，期望要根据推断类型传入对应数量的参数，否则报红，具体见`/workspaces/alova/test/browser/hooks/vue/useRequest-http.spec.ts:376`，将`send(3)`改为`send()`也不会报错。
2. useRequest返回的data，以及send函数返回的data类型错误，导致单元测试报错，期望要根据R自动推断，具体见`/workspaces/alova/test/browser/hooks/vue/useRequest-http.spec.ts:376`
3. 实现稍微复杂了点，建议直接推断参数类型，而不是整个函数导致后面的类型转换也复杂起来了，一个简单的示例：
```ts


function useRequest<Arg extends any[]>(handler: (...args: Arg) => string) {
  handler;
  return {
    send: (...args: [...Arg, ...any[]]) => {
      args;
    }
  };
}


const tt = useRequest((a: number, b: string) => {
  a; b;
  return '';
});

tt.send(1, 'a', 'c', true)
```

2024-06-09 12:10 UTC, MeetinaXD commented
😃 非常感谢你的工作！PR 的实现十分接近我们想要的效果，这边可以补充一些单元测试！

由于 alova 目前使用的 jest 框架并不支持编写针对类型的测试（vitest 可以）。

建议可以通过一个 ts 文件来完成，例如：
```typescript
// utils.d.ts 补充
declare type ExpectTrue<T extends true> = T;
declare type ExpectFalse<T extends false> = T;

declare type Equal<X, Y> =
  (<T>() => T extends X ? 1 : 2) extends
  (<T>() => T extends Y ? 1 : 2) ? true : false;
```
```typescript
// sendArgsType.spec.ts
import { useRequest } from '@/index';
import VueHook from '@/predefine/VueHook';
import { Ref } from 'vue';
import { getAlovaInstance } from '~/test/utils';
const alovaInst = getAlovaInstance(VueHook);

interface NestType {
  name: string;
  age: number;
}

const Getter = (name: string, nested: NestType) => alovaInst.Get<number>('test', { params: { name, nested } });
const GetterAny = alovaInst.Get<string>('test');
const GetterAnyHandler = () => alovaInst.Get<string>('test');

const hookA = useRequest(Getter);
const hookB = useRequest(GetterAny);
const hookC = useRequest(GetterAnyHandler);

export type TestCase1 = ExpectTrue<Equal<Parameters<typeof hookA.send>, [string, NestType, ...any[]]>>;
export type TestCase2 = ExpectTrue<Equal<Parameters<typeof hookB.send>, [...any[]]>>;
export type TestCase3 = ExpectTrue<Equal<Parameters<typeof hookB.send>, Parameters<typeof hookC.send>>>;

export type TestCase4 = ExpectTrue<Equal<typeof hookA.data, Ref<number>>>;
export type TestCase5 = ExpectTrue<Equal<typeof hookA.data, Ref<number>>>;
export type TestCase6 = ExpectTrue<Equal<typeof hookA.data, Ref<number>>>;

// expected error
export type TestCase7 = ExpectFalse<Equal<Parameters<typeof hookA.send>, [...any[]]>>;
```

然后通过 `tsc --noEmit` 应该可以实现到单测的效果。

2024-06-11 03:04 UTC, merged

2024-06-11 03:09 UTC, JOU-amjs commented
:tada: This PR is included in version 2.21.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/alova/v/2.21.0)
- [GitHub release](https://github.com/alovajs/alova/releases/tag/v2.21.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: