use StateExport for type inference instead of generics
alovajs/alova pull request #419
Opened 2024-06-28 04:07 UTC by MeetinaXD

**这个 PR 是什么类型？/ What type of PR is this?**

- [ ] 错误修复 (Bug Fix)
- [ ] 新功能 (Feature)
- [x] 代码重构 (Refactor)
- [ ] TypeScript 类型定义修改 (Typings)
- [ ] 文档修改 (Docs)
- [ ] 代码风格更新 (Code style update)
- [ ] 其他，请描述 (Other, please describe):

**这个 PR 做了什么？/ What does this PR do?**

使用 StateExport 导出类型，通过字符串而非具体框架类型推断最终导出类型。

**测试 / Testing**

所有测试已通过。

2024-06-29 08:54 UTC, JOU-amjs requested changes

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +  ComputedExport: T;
1. 我看`StatesExport`都是拿来extends的，里面这个干脆直接就any好了，也省了一个泛型参数
2. 已经把Export拆分成了`StateExport`和`ComputedExport`，那Export就没用了，可以不需要了

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +  create: (initialValue: any, referingObject: ReferingObject) => SE['StateExport'];
这里应该是`SE['State']`

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +  computed: (getter: () => any, deps: SE['Export'][], referingObject: ReferingObject) => SE['Computed'];
deps改成`SE['StateExport'] | SE['ComputedExport']`吗

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +  export?: (state: SE['State'], referingObject: ReferingObject) => SE['Export'];
返回值也可以改成`SE['StateExport'] | SE['ComputedExport']`

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +      SE
这里因为SE里应该就包含`  State,
      Computed,
      Watched,
      Export`了，就不需要再要它们了

2024-06-29 08:54 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +    SE
这里因为SE里应该就包含`  State,
      Computed,
      Watched,
      Export`了，就不需要再要它们了

2024-07-01 05:05 UTC, MeetinaXD commented on packages/alova/typings/index.d.ts
> +  ComputedExport: T;
1. 就现在的实现而言，这样改是可以的。这个 T 现在更多起的是一个语义上的作用，我觉得可以默认给 T 一个 any
2. 可以的

2024-07-04 02:07 UTC, JOU-amjs commented on packages/alova/typings/index.d.ts
> +  ComputedExport: T;
其实这个`any | T`得出的类型，无论T是什么都会返回any

2024-07-06 08:20 UTC, MeetinaXD commented on packages/alova/typings/index.d.ts
> +  ComputedExport: T;
疏忽了，已修正

2024-07-07 07:13 UTC, JOU-amjs approved these changes

2024-07-07 07:20 UTC, merged