feat(stateshook-solid): add unfinished feature
alovajs/alova pull request #479
Opened 2024-07-24 12:24 UTC by theqianqiu

**相关 Issue / Related Issue**

[Issue ID]

**这个 PR 是什么类型？/ What type of PR is this?**

- [ ] 错误修复 (Bug Fix)
- [x] 新功能 (Feature)
- [ ] 代码重构 (Refactor)
- [ ] TypeScript 类型定义修改 (Typings)
- [ ] 文档修改 (Docs)
- [ ] 代码风格更新 (Code style update)
- [ ] 其他，请描述 (Other, please describe):

**这个 PR 做了什么？/ What does this PR do?**

[简要描述所做更改 / Describe the changes briefly]

**文档 / Docs**

[此次 PR 的文档 / Docs for this PR]

**测试 / Testing**

[描述测试结果 / Describe the test results.]

2024-07-30 05:34 UTC, MeetinaXD commented
感谢 PR！目前发现了以下问题：

1. 过半的更改都是关于修复 `'React' must be in scope when using JSX` 这个问题，请考虑在其他 PR 解决，或修改 PR 描述；
2. 出现了无意义提交，只影响代码风格而不产生实际更改的修改不应该提交；
3. 修改了根 tsconfig.json，具体请看文件中的描述；
4. 新增的测试没通过

稍后记得补充 changeset 😃

2024-07-30 05:35 UTC, MeetinaXD requested changes

2024-07-30 05:35 UTC, MeetinaXD commented on tsconfig.base.json
> +    "jsx": "react-jsx",
这里修改的原因是什么？

如有需要，请在 client 下的 tsconfig 中修改，以免影响其他模块。

2024-07-30 05:35 UTC, MeetinaXD commented on packages/alova/typings/serverhook.d.ts
请不要提交无意义更改

2024-08-09 16:04 UTC, JOU-amjs reviewed
综合所述，可能还有些需要修改之处，本来想直接给修改的，但这么久跟下来solid单测集成进来确实存在一些困难，你也可以尝试修改，或者我后面再抽空修改下

2024-08-09 16:04 UTC, JOU-amjs commented on packages/client/test/solid/statesHook.solid.spec.tsx
> +    waitFor(() => {
没有添加`await`时检测不到回调内部的期望值，当添加上`await`时此单测是报错的，下同

2024-10-31 12:38 UTC, merged